# sympy 求导，并带入值计算

## scipy求导

In [2]:
import numpy as np
from scipy.misc import derivative

def f(x):
    return x ** 5

for x in range(1, 4):
    print(derivative(f, x, dx=1e-6))

4.999999999866223
80.00000000230045
405.00000005749826


## sympy表达式求导

In [3]:
from sympy import *
def sympy_derivative():
    
    # 定义表达式的变量名称
    x1, x2 = symbols("x1 x2")
    
    # 定义表达式内容
    y = x1 ** 2 + x2 ** 2
    
    # 计算 x2 对应的偏导数
    return diff(y, x2)

sympy_derivative()

2*x2

## sympy代入数值计算

In [4]:
func = sympy_derivative()
print(func)
# 把 x2=6 代入计算
print(func.evalf(subs = {"x2": 6}))

2*x2
12.0000000000000


# NumPy随机数

In [27]:
import numpy as np
np.random.seed(666)

## np.random.randn() 返回一个或一组服从标准正态分布的随机样本

In [2]:
np.random.rand()

0.8560512565234065

In [3]:
np.random.randn(1)

array([1.13469674])

In [4]:
np.random.randn(2)

array([-2.21831954,  0.43851329])

In [5]:
np.random.randn(4, 3, 2)

array([[[-0.83528672,  0.07273229],
        [ 0.40176945,  0.27295681],
        [ 0.77212448,  1.18404845]],

       [[-0.69872787,  0.24982161],
        [-1.77572357,  0.65237069],
        [ 0.76002915,  0.08361761]],

       [[ 0.16988358, -0.05741235],
        [ 0.71279305, -1.05235799],
        [-2.50075474, -1.23334483]],

       [[-0.04175812,  0.04526483],
        [-1.43024691,  0.50720395],
        [-1.38424516, -1.52701412]]])

## np.random.rand() 返回一个或一组服从0～1均匀分布的随机样本

In [6]:
np.random.rand()

0.9941148219323209

In [7]:
np.random.rand(1)

array([0.30462463])

In [8]:
np.random.rand(2)

array([0.76303015, 0.17200856])

In [9]:
np.random.rand(4, 3, 2)

array([[[0.80297988, 0.54166302],
        [0.91534073, 0.76528171],
        [0.69960099, 0.03436795]],

       [[0.73204564, 0.32415741],
        [0.94676434, 0.56368596],
        [0.42283175, 0.79321518]],

       [[0.99189392, 0.04346883],
        [0.59064386, 0.37028232],
        [0.05200304, 0.74593079]],

       [[0.18382363, 0.40514002],
        [0.42654747, 0.60730168],
        [0.52064997, 0.53825705]]])

## np.random.randint() 返回随机整数或整型数组[low, high)

In [10]:
?np.random.randint

In [19]:
np.random.randint(1)

0

In [21]:
np.random.randint(1, size=(2, 2))  # Low=1, high=None, size=(2, 2)

array([[0, 0],
       [0, 0]])

In [23]:
np.random.randint(1, 20, size=(4, 4), dtype="uint8")

array([[16, 14,  6, 18],
       [ 6, 14, 14,  7],
       [15, 12,  2, 14],
       [14,  7, 11,  3]], dtype=uint8)